[package]
name = "base-h1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
async-dup = "1.2.2"
async-h1 = "2.3.3"
futures = "0.3.21"
http-types = "2.12.0"
smol = "1.2.5"
