[package]
name = "sozu"
version = "0.1.0"
authors = ["Begley Brothers Inc. <begleybrothers@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sozu = "0.13.1"
